name: v04
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.2.2
  dotenv: ^4.2.0
# När du lagt till ny dependency, kör 'dart pub get' för att installera den.


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
